### PR TITLE
Fix: Only disconnect on onmount or if room changes

### LINKED ISSUE #249: Unable to enter livekit room with newest version of components-react
### Select which package(s) are affected

\@livekit/components-react

### Describe the bug

After upgrading to `0.1.20` i have this error. And i am unable enter to room entirely. This error is not present on version 0.1.18. 

Ekran Resmi 2023-01-20 10 59 32

### Reproduction

-

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.63 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - ~/.nvm/versions/node/v18.2.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.9.0 - ~/.nvm/versions/node/v18.2.0/bin/npm
  Browsers:
    Brave Browser: 108.1.46.153
    Chrome: 109.0.5414.87
    Firefox Developer Edition: 109.0
    Safari: 16.2
  npmPackages:
    livekit-client: ^1.6.2 => 1.6.2
```

### Severity

blocking all usage of LiveKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lukasIO**
Fixes #249

### CODE REVIEW

File: packages/react/src/components/LiveKitRoom.tsx [hunk 1]
```diff
@@ -163,12 +163,14 @@ export function useLiveKitRoom(props: LiveKitRoomProps) {
     } else {
       room.disconnect();
     }
+  }, [connect, token, connectOptions, room, onError, serverUrl]);
```
Comment (Ocupe) [inline packages/react/src/components/LiveKitRoom.tsx:166]: Missing dependency `simulateParticipants`

**Review by Ocupe — APPROVED** [review]
👍
